In [30]:
import sys
sys.path.insert(0, '..')
import numpy as np
from BinaryTokenizer import BinaryTokenizer

ImportError: attempted relative import with no known parent package

In [10]:
data = np.load('../data/augmented_and_padded_data.npz')
print(data)
melody_pcps = data['melody_pcps']
chord_pcps = data['chord_pcps']

NpzFile '../data/augmented_and_padded_data.npz' with keys: melody_pcps, chord_pcps


In [25]:
print('melody_pcps.shape: ', melody_pcps.shape)
print('chord_pcps.shape: ', chord_pcps.shape)
print(melody_pcps[0,:,:])
print(chord_pcps[0,:,:])

melody_pcps.shape:  (5328, 129, 12)
chord_pcps.shape:  (5328, 129, 12)
[[1 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 1]
 [1 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[1 0 1 ... 1 0 0]
 [0 0 1 ... 0 0 1]
 [1 0 1 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
binTok = BinaryTokenizer()

In [20]:
tok_melody = binTok.fit_transform( melody_pcps )
tok_chord = binTok.fit_transform( chord_pcps )

In [24]:
print('tok_melody.shape: ', tok_melody.shape)
print('tok_chord.shape: ', tok_chord.shape)
print(tok_melody[0,:])
print(tok_chord[0,:])

tok_melody.shape:  (5328, 129)
tok_chord.shape:  (5328, 129)
[2052    1 2052    1   17    4   17    4 2052    1 2052   17  128  128
 1152  256 1152  256  257 1024  257 1024 1152  256 1152  257    8   16
 2052    1 2052    1   17    4   17    4 2052    1 2052   17   16   16
    4   16   64  128   16   64  640 2052    1 2052  129 2048 2048    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0]
[2628  593 2628  593 2193 2372  657 1172 2628  593 2628  593 2193 2193
 1188  293 1188  293  393 1172  297 1097 1188  293 1188  293  393  593
 2628  593 2628  593 2193 2372  657 1172 2628  593 2628  593  658 1174
 2628 1170 2244 1170 2628 2628  586  657 2340 2628  593 2196 2196    0